### PR TITLE
Two Sum By Sriragavi P

### PR DESCRIPTION
**Pull request by sriragavip**
completed , pls check and update my name in doc

### CODE REVIEW

**Comment by dhruvabhat24** [comment]
Add code explanation

**Comment by dhruvabhat24** [comment]
ALSO WHILE SOLVING THE PROBLEM KEEP THE TIMER ON IN LEETCODE

**Comment by sriragavip** [comment]
from next problem , i  will do that

**Comment by dhruvabhat24** [comment]
For today's problem add code explanation

**Pull request closed without merging**
