### PR TITLE
Day 4: product of all except the self

### PR DESCRIPTION
**Pull request by himanshukhurana2324**

### CODE REVIEW

**Comment by dhruvabhat24** [comment]
Still the same conflict has been faced. No need o close this pull request. 
The error was the the readme file. I thing you have cloned the repository to your system. So kindly in VS code once sync the files. So that in future these kind of problems will not occur

**Comment by dhruvabhat24** [comment]
This pull request willbe merged after this kindly update the readme with past two days details

**Comment by himanshukhurana2324** [comment]
error: invalid path 'Blind 75 LeetCode/Abhiram Hegde /Two Sum/README.md'
error: invalid path 'Blind 75 LeetCode/Abhiram Hegde /Two Sum/solution.java'
error: invalid path 'Blind 75 LeetCode/Abhiram Hegde /readme.md'

Please check for these files, creating issues in push and pull requests

**Comment by dhruvabhat24** [comment]
Once Sync the rpo and check

**Comment by himanshukhurana2324** [comment]
error: invalid path 'Blind 75 LeetCode/Abhiram Hegde /Two Sum/README.md'
error: invalid path 'Blind 75 LeetCode/Abhiram Hegde /Two Sum/solution.java'
error: invalid path 'Blind 75 LeetCode/Abhiram Hegde /readme.md'

The issue is with the directory . Please remove the directory and ask the person to push again . 
i have done all the ways including sync

**Pull request merged**
