### PR TITLE
Day 4: Blind 75 Leetcode done

### PR DESCRIPTION
**Pull request by Rajsatyammm**
Day 4: Product of Array Except Self done on 08/02/2024

### CODE REVIEW

**Comment by dhruvabhat24** [comment]
Update the readme...

**Comment by Rajsatyammm** [comment]
Okk, for today's PR number

**Comment by dhruvabhat24** [comment]
Yes ..

**Comment by Rajsatyammm** [comment]
Ok sure i will do it..

**Comment by dhruvabhat24** [comment]
From now onwards daily after merging the pr I will remind you to update the pr.
I am doing this because a lot of the members are not updating it daily so I will remind everyone as I merge their pr.

**Pull request merged**
