### PR TITLE
Shubham Sharma

### PR DESCRIPTION
**Pull request by Shuubhhaammm**
Yesterday, I was confused with GitHub contribution, now I understand how to contribute by fork and all stuff.
I have added two folders inside my folder, as I started this challenge yesterday.

Please check this pull request and let me know if there is any problem.

### CODE REVIEW

**Comment by dhruvabhat24** [comment]
Add the solution link
Follow the steps below  
 - in solution column type [Solution](paste the github folder link)
 - for day one  [Solution](Two sum folder link)
 - follow the same for upcoming days also in the merged pull request number add the same number for both rows after that i will merge the pull request so there is no need to raise another pull request

**Comment by dhruvabhat24** [comment]
> Yesterday, I was confused with GitHub contribution, now I understand how to contribute by fork and all stuff. I have added two folders inside my folder, as I started this challenge yesterday.
> 
> Please check this pull request and let me know if there is any problem.

If ypou have any doubts regarding the contribution guideline you can ask it in discussion session 
# Important thing to do 
- You have not followed one guideline of contributing. i.e keeping timer on in leetcode while solving problem 
- for the coming days keep it on otherwise pr will be marked as invalid

**Comment by Shuubhhaammm** [comment]
> > Yesterday, I was confused with GitHub contribution, now I understand how to contribute by fork and all stuff. I have added two folders inside my folder, as I started this challenge yesterday.
> > Please check this pull request and let me know if there is any problem.
> 
> If ypou have any doubts regarding the contribution guideline you can ask it in discussion session
> 
> # Important thing to do
> * You have not followed one guideline of contributing. i.e keeping timer on in leetcode while solving problem
> * for the coming days keep it on otherwise pr will be marked as invalid

sorry sir, I forget this step. I will do this from next time.

**Comment by Shuubhhaammm** [comment]
> Add the solution link Follow the steps below
> 
> * in solution column type [Solution](paste the github folder link)
> * for day one  [Solution](Two sum folder link)
> * follow the same for upcoming days also in the merged pull request number add the same number for both rows after that i will merge the pull request so there is no need to raise another pull request

done sir!

**Pull request merged**
