### PR TITLE
Best Time To Buy and Sell Stock

### PR DESCRIPTION
**Pull request by Dev-Nithish**
**Code Explanation:**

**1. Initialization:**

- `minPrice`: Set to `Integer.MAX_VALUE` to ensure it's updated with the first price.
- `max_profit`: Set to 0, representing the initial maximum profit.

**2. Iteration:**

- The `for` loop iterates through each price in the `prices` array.

**3. Updating `minPrice`:**

- If the current price `prices[i]` is less than `minPrice`, update `minPrice` to track the lowest price seen so far.

**4. Calculating Potential Profit:**

- Calculate the difference between the current price and `minPrice` (`prices[i] - minPrice`).
- If this difference is greater than `max_profit`, it indicates a potentially more profitable scenario.

**5. Updating `max_profit`:**

- If `prices[i] - minPrice > max_profit`, update `max_profit` to the current difference, storing the maximum potential profit.

**6. Return Value:**

- After iterating through all prices, `max_profit` holds the maximum potential profit.
- The function returns `max_profit`.

**Key Points:**

- The code efficiently finds the maximum profit using a single loop.
- It assumes only one buy and one sell transaction.
- For multiple buy-sell transactions, different algorithms would be needed.

### CODE REVIEW

**Comment by Dev-Nithish** [comment]
Screenshot 2024-02-09 192423

**Comment by Dev-Nithish** [comment]
**Code Explanation:**

**1. Initialization:**

- `minPrice`: Set to `Integer.MAX_VALUE` to ensure it's updated with the first price.
- `max_profit`: Set to 0, representing the initial maximum profit.

**2. Iteration:**

- The `for` loop iterates through each price in the `prices` array.

**3. Updating `minPrice`:**

- If the current price `prices[i]` is less than `minPrice`, update `minPrice` to track the lowest price seen so far.

**4. Calculating Potential Profit:**

- Calculate the difference between the current price and `minPrice` (`prices[i] - minPrice`).
- If this difference is greater than `max_profit`, it indicates a potentially more profitable scenario.

**5. Updating `max_profit`:**

- If `prices[i] - minPrice > max_profit`, update `max_profit` to the current difference, storing the maximum potential profit.

**6. Return Value:**

- After iterating through all prices, `max_profit` holds the maximum potential profit.
- The function returns `max_profit`.

**Key Points:**

- The code efficiently finds the maximum profit using a single loop.
- It assumes only one buy and one sell transaction.
- For multiple buy-sell transactions, different algorithms would be needed.

**Comment by Dev-Nithish** [comment]
done

**Comment by Dev-Nithish** [comment]
done

**Comment by Dev-Nithish** [comment]
done

**Comment by dhruvabhat24** [comment]
Add the codes inside the folders. Kindly open new pull request. Follow guidelines. 
1. Create a folder with problem title
2. Create a readme.kd file add explanation of the code in it 
3. Create another file with code extension
4. Commit both files 
5. In the main readme update the solution and change the status as solved. 
6. Create the pull request 
7. Attach the screenshot in the pullrequest
8. Wait for the review

**Pull request closed without merging**
