### PR TITLE
Create code

### PR DESCRIPTION
**Pull request by Ananya01Agrawal**

### CODE REVIEW

**Comment by dhruvabhat24** [comment]
@Ananya01Agrawal Follow the guidelines. If you are facing issues with the guidelines then open a discussion in Q&A section. Feel free to share your problem.

**Comment by Ananya01Agrawal** [comment]
ok sir, for sure

**Review by dhruvabhat24 — CHANGES_REQUESTED** [review]
No need to add entire content in the readme file.
Add the contents provided in [template.md](https://github.com/Lets-code-with-us/DSA-Cracker/blob/main/Blind%2075%20LeetCode/template.md) file

**Comment by dhruvabhat24** [comment]
Also I think you have not registered for the event

**Comment by Ananya01Agrawal** [comment]
I have registered for the event and also made changes in the  readme file

**Review by dhruvabhat24 — APPROVED** [review]

**Comment by dhruvabhat24** [comment]
You can start adding the code with explanation 
Inside Ananya Agrawal folder crate a folder with problem title 
- Create two files inside the folder 
- explanation ofthe code in readme 
- code with extension
- keep the timer on while solving the problem in leetcode
- take a screensot of submission status 
- attach the screenshot in the next pull-request
- once the pull request is merged update the readme file with the merged pull equest number and also update the status of problem as solved

**Pull request merged**
