### PR TITLE
Day 4

### PR DESCRIPTION
**Pull request by Shuubhhaammm**
Product of Array Expect Self ✅

### CODE REVIEW

**Review by dhruvabhat24 — CHANGES_REQUESTED** [review]
Pull request numbers are not matching with the actual pull request numbers make the changes and push. After the chages made once again i will review if those are valid then the pull request will be merged

**Comment by dhruvabhat24** [comment]
@Shuubhhaammm Don the changes before 24 hrs of opening pr 
2 hrs remaining after that I will close this pr as invalid and I won't be counted as streak

**Comment by Shuubhhaammm** [comment]
sorry sir, yesterday I was busy in a marriage.
I don't understand what to change.

**Comment by Shuubhhaammm** [comment]
image

are you talking about the commit title "Day 4" ??

**Comment by dhruvabhat24** [comment]
No merged pull request number inside the readme table

**Comment by dhruvabhat24** [comment]
For the last program u have mention as 104 but for earlier programs you have not mentioned clearly

**Comment by Shuubhhaammm** [comment]
I got you sir, and I have made the changes! 
Thank you for your guidance.

**Pull request merged**
