### PR TITLE
new_code

### PR DESCRIPTION
**Pull request by ChahatRajput1**

### CODE REVIEW

**Review by dhruvabhat24 — CHANGES_REQUESTED** [review]
Main readme file is corrected 
image

**Comment by ChahatRajput1** [comment]
I updated whole file regularly but don't know what problem arises now

**Comment by dhruvabhat24** [comment]
The issues is with your main readme file there in the table contents are repeated I have attached the screenshot You can check there

**Comment by ChahatRajput1** [comment]
I made changes but now where is the rest of codes which I solved from beginning that is not present in readme file

**Comment by dhruvabhat24** [comment]
Your repository is 1251 commits behind. Kindly synk the repository. You will get to see your readme and in solutions.

**Comment by ChahatRajput1** [comment]
ok thank you

**Pull request merged**
